/**
 * FVS Keyword File Export
 *
 * Generates Forest Vegetation Simulator (USDA Forest Service) keyword files
 * (.key) from the user's planting plan. Users can run these through FVS
 * Suppose or command-line FVS for validated growth projections.
 *
 * FVS keyword file format reference:
 *   Essential FVS: A User's Guide (Dixon 2002, GTR-INT-327)
 */

import { FVS_SPECIES_CODES, detectFvsVariant, getFvsCode } from '../data/fvsSpeciesCodes';
import { estimateAreaAcres } from '../models/forestryModel';

/**
 * Generate a complete FVS keyword file string from the user's stand data.
 *
 * @param {Object} params
 * @param {Array} params.trees - array of tree objects
 * @param {Map|Object} params.speciesMap - species lookup
 * @param {Object|null} params.prescription - silvicultural prescription
 * @param {number} params.siteIndex - site index multiplier (0.7-1.3)
 * @param {string} params.projectName - project name
 * @param {number} params.lat - latitude
 * @param {number} params.lng - longitude
 * @param {number} [params.projectionYears=80] - total projection years
 * @returns {string} FVS keyword file content
 */
export function generateFvsKeywordFile({
  trees,
  speciesMap,
  prescription,
  siteIndex,
  projectName,
  lat,
  lng,
  projectionYears = 80,
}) {
  const variant = detectFvsVariant(lat || 40, lng || -75);
  const variantLabels = {
    ne: 'Northeast (NE)', sn: 'Southern (SN)', pn: 'Pacific NW (PN)',
    cr: 'Central Rockies (CR)', ci: 'Inland Empire (CI)', ca: 'Inland California (CA)',
  };
  const variantLabel = variantLabels[variant] || variant.toUpperCase();
  const areaAcres = estimateAreaAcres(trees);
  const numCycles = Math.ceil(projectionYears / 10);

  const getSpecies = (id) => {
    if (speciesMap instanceof Map) return speciesMap.get(id);
    return speciesMap?.[id];
  };

  const lines = [];

  lines.push(`!!`);
  lines.push(`!! FVS Keyword File`);
  lines.push(`!! Generated by Tree Planting Visualizer`);
  lines.push(`!! Project: ${projectName || 'Untitled'}`);
  lines.push(`!! Location: ${(lat || 0).toFixed(4)}, ${(lng || 0).toFixed(4)}`);
  lines.push(`!! Variant: ${variantLabel}`);
  lines.push(`!! Date: ${new Date().toISOString().split('T')[0]}`);
  lines.push(`!!`);
  lines.push(`!! NOTE: This file is for validation purposes. Run through FVS`);
  lines.push(`!! Suppose (https://www.fs.usda.gov/fvs/) for calibrated projections.`);
  lines.push(`!!`);
  lines.push(``);

  // Stand identification
  lines.push(`STDIDENT`);
  lines.push(`${(projectName || 'STAND1').substring(0, 26).replace(/\s+/g, '_')}`);

  // Time configuration
  lines.push(`TIMEINT            0        10`);
  lines.push(`NUMCYCLE          ${numCycles}`);
  lines.push(`INVYEAR         2025`);

  // Site index -- convert our multiplier (0.7-1.3) to a numeric SI
  // FVS expects species-specific SI (height in feet at base age 50)
  // We approximate: SI70 baseline, scaled by our multiplier
  const numericSI = Math.round(70 * (siteIndex || 1.0));
  lines.push(``);
  lines.push(`!! Site Index (base age 50, estimated from soil data)`);
  lines.push(`SITECODE          ${numericSI}`);

  // Design -- sampling design for the tree list
  // We use a fixed-area plot covering our estimated acreage
  lines.push(``);
  lines.push(`!! Plot design: fixed-area plot`);
  lines.push(`DESIGN             0         1       999         1         0    ${areaAcres.toFixed(2)}`);

  // Tree list
  lines.push(``);
  lines.push(`!! Tree List`);
  lines.push(`!! Columns: plot, tree#, count, history, species, DBH, DG, Ht, HtTopK, CrRatio, Damage, TPA_expand`);
  lines.push(`TREELIST           0`);

  // Compute TPA expansion factor: each tree represents itself
  const tpaExpansion = 1.0 / Math.max(0.01, areaAcres);

  let unmappedSpecies = [];
  let fallbackSpecies = []; // species that used a different variant's code
  let treeNum = 0;

  for (const tree of trees) {
    treeNum++;
    const sp = getSpecies(tree.speciesId || tree.species?.id);
    if (!sp) continue;

    const sciName = sp.scientificName || '';
    const result = getFvsCode(sciName, variant);

    if (!result) {
      unmappedSpecies.push(sp.name || sciName);
      continue;
    }

    if (result.fallback) {
      fallbackSpecies.push({
        name: sp.name || sciName,
        code: result.code,
        fromVariant: result.variant.toUpperCase(),
      });
    }

    // FVS TREELIST format (free format after header):
    // Plot TreeID Count History Species DBH DG Ht HtTopK CrRatio Damage TPA
    const dbh = 1.0; // planting size: 1" seedling
    const ht = 5; // 5 ft seedling
    const cr = 60; // 60% crown ratio (percentage, not decimal for FVS)

    lines.push(
      `     1  ${String(treeNum).padStart(4)}     1     1  ` +
      `${result.code.padEnd(3)} ` +
      `${dbh.toFixed(1).padStart(5)} ` +
      `  0.0 ` +
      `${String(ht).padStart(4)} ` +
      `   0 ` +
      `${String(cr).padStart(3)} ` +
      `  0 ` +
      `${tpaExpansion.toFixed(1).padStart(7)}`
    );
  }

  lines.push(`-999`); // End of tree list

  // Prescription keywords
  if (prescription && prescription.actions && prescription.actions.length > 0) {
    lines.push(``);
    lines.push(`!! Silvicultural Prescription: ${prescription.name}`);
    lines.push(`!! ${prescription.description || ''}`);

    for (const action of prescription.actions) {
      lines.push(``);
      lines.push(`!! ${action.label} at year ${action.year}`);

      const schedYear = 2025 + action.year;

      switch (action.type) {
        case 'pct':
          // Pre-commercial thinning -- THINDBH from below
          lines.push(`THINDBH  ${schedYear}         0.0       6.0         1         ${(1 - action.removePct).toFixed(2)}`);
          break;

        case 'thin-below':
          // Commercial thin from below
          lines.push(`THINDBH  ${schedYear}         ${(action.minMerchDbh || 5).toFixed(1)}      99.0         1         ${(1 - action.removePct).toFixed(2)}`);
          break;

        case 'thin-above':
        case 'shelterwood-seed':
          // Thin from above (remove co-dominants)
          lines.push(`THINDBH  ${schedYear}         ${(action.minMerchDbh || 8).toFixed(1)}      99.0         2         ${(1 - action.removePct).toFixed(2)}`);
          break;

        case 'clearcut':
        case 'shelterwood-removal':
          // Clearcut
          lines.push(`CLEARCUT ${schedYear}         ${(action.minMerchDbh || 1).toFixed(1)}`);
          break;

        case 'selection':
          // Single-tree selection (thin from above, largest first)
          lines.push(`THINDBH  ${schedYear}         ${(action.minMerchDbh || 10).toFixed(1)}      99.0         2         ${(1 - action.removePct).toFixed(2)}`);
          break;

        case 'sanitation':
          // Sanitation -- thin smallest/weakest
          lines.push(`THINDBH  ${schedYear}         0.0      99.0         1         ${(1 - action.removePct).toFixed(2)}`);
          break;

        default:
          lines.push(`!! Unmapped action type: ${action.type}`);
      }
    }
  }

  // Output requests
  lines.push(``);
  lines.push(`!! Output options`);
  lines.push(`TREELIST           0`);
  lines.push(`ECHOSUM`);
  lines.push(`COMPUTE            0`);
  lines.push(`END`);
  lines.push(`PROCESS`);
  lines.push(`STOP`);

  // Add fallback species note
  if (fallbackSpecies.length > 0) {
    const unique = [...new Map(fallbackSpecies.map(s => [s.name, s])).values()];
    lines.push(``);
    lines.push(`!!`);
    lines.push(`!! NOTE: The following species are not native to the ${variant.toUpperCase()} variant`);
    lines.push(`!! and were mapped using codes from another variant. Verify these are`);
    lines.push(`!! appropriate for your FVS run or substitute manually:`);
    for (const s of unique) {
      lines.push(`!!   - ${s.name}: code '${s.code}' (from ${s.fromVariant} variant)`);
    }
    lines.push(`!!`);
  }

  // Add unmapped species warning as comment at the end
  if (unmappedSpecies.length > 0) {
    const unique = [...new Set(unmappedSpecies)];
    lines.push(``);
    lines.push(`!!`);
    lines.push(`!! WARNING: The following species could not be mapped to ANY FVS variant`);
    lines.push(`!! and were EXCLUDED from this keyword file:`);
    for (const name of unique) {
      lines.push(`!!   - ${name}`);
    }
    lines.push(`!! Consider manually adding these as substitute species in FVS.`);
    lines.push(`!!`);
  }

  return lines.join('\n');
}

/**
 * Trigger a browser download of the FVS keyword file.
 */
export function downloadFvsKeywordFile(content, filename) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || 'stand_export.key';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
