/**
 * Professional multi-page PDF report generation for CanopyViz.
 *
 * Pages:
 *   1. Cover + Summary
 *   2. Species Breakdown
 *   3. Growth Projections (stand metrics by decade)
 *   4. Management Schedule + Financial Analysis
 *   5. Environmental Impact
 *   6. Methodology Notes
 */

import { jsPDF } from 'jspdf';
import {
  calculateCanopyArea,
  calculateCO2,
  calculateTempReduction,
  calculateCarbonOverTime,
  formatCO2,
} from '../utils/calculations';
import { projectStand, projectStandTimeSeries } from '../models/forestryModel';
import { enrichHarvestEvent, analyzeInvestment, treeHarvestValue, classifyProduct } from '../models/forestFinance';
import { standAnnualServices } from '../models/ecosystemServices';
import { analyzeCarbonCredits } from '../models/carbonCredits';

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 15;
const CONTENT_W = PAGE_W - 2 * MARGIN;

// Color palette
const DARK_GREEN = [15, 26, 15];
const EMERALD = [52, 211, 153];
const MED_GREEN = [30, 80, 30];
const LIGHT_GREEN = [240, 248, 240];
const ROW_ALT = [248, 252, 248];
const MUTED = [120, 140, 120];
const DARK_TEXT = [40, 60, 40];
const HEADER_TEXT = [60, 90, 60];

function addPageFooter(doc, pageNum, totalPages, projectName) {
  doc.setFillColor(...DARK_GREEN);
  doc.rect(0, PAGE_H - 12, PAGE_W, 12, 'F');
  doc.setTextColor(...MUTED);
  doc.setFontSize(6);
  doc.text('Generated by CanopyViz — Tree Planting Visualizer', MARGIN, PAGE_H - 5);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W / 2, PAGE_H - 5, { align: 'center' });
  doc.text(projectName || '', PAGE_W - MARGIN, PAGE_H - 5, { align: 'right' });
}

function addSectionHeader(doc, y, title) {
  doc.setTextColor(...MED_GREEN);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, y);
  doc.setDrawColor(...EMERALD);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y + 2, MARGIN + CONTENT_W, y + 2);
  return y + 10;
}

function fmtDollar(n) {
  if (n == null || isNaN(n)) return '$0';
  const abs = Math.abs(n);
  const sign = n < 0 ? '-' : '';
  if (abs >= 1000000) return `${sign}$${(abs / 1000000).toFixed(1)}M`;
  if (abs >= 1000) return `${sign}$${(abs / 1000).toFixed(1)}k`;
  return `${sign}$${Math.round(abs)}`;
}

function fmtNum(n) {
  if (n == null || isNaN(n)) return '0';
  return Math.round(n).toLocaleString();
}

/**
 * Generate a comprehensive multi-page PDF report.
 */
export async function generatePDF({
  mapRef,
  trees,
  speciesMap,
  address,
  projectName,
  prescription,
  siteIndex = 1.0,
  projectionYear = 0,
}) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pName = projectName || 'Untitled Plan';
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Pre-compute data
  const getSpecies = (id) => speciesMap instanceof Map ? speciesMap.get(id) : speciesMap?.[id];
  const canopyArea = calculateCanopyArea(trees, speciesMap);
  const co2 = calculateCO2(trees, speciesMap);
  const tempReduction = calculateTempReduction(trees, speciesMap);

  const projection80 = projectStand(trees, speciesMap, 80, siteIndex, null, prescription);
  const timeSeries = projectStandTimeSeries(trees, speciesMap, 80, siteIndex, null, prescription, 10);
  const currentProjection = projectStand(trees, speciesMap, projectionYear || 0, siteIndex, null, prescription);

  // Species count
  const speciesCount = {};
  trees.forEach(t => { speciesCount[t.speciesId] = (speciesCount[t.speciesId] || 0) + 1; });
  const speciesList = Object.entries(speciesCount)
    .map(([id, count]) => ({ ...getSpecies(id), id, count }))
    .filter(s => s.name)
    .sort((a, b) => b.count - a.count);

  const uniqueSpeciesCount = speciesList.length;
  const totalPages = 6;

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 1: Cover + Summary
  // ═══════════════════════════════════════════════════════════════════════
  doc.setFillColor(...DARK_GREEN);
  doc.rect(0, 0, PAGE_W, 45, 'F');

  doc.setTextColor(...EMERALD);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Forest Management Report', MARGIN, 20);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 220, 180);
  doc.text(pName, MARGIN, 30);
  if (address) {
    doc.setFontSize(10);
    doc.text(address, MARGIN, 37);
  }
  doc.setTextColor(...MUTED);
  doc.setFontSize(8);
  doc.text(dateStr, PAGE_W - MARGIN, 37, { align: 'right' });

  let y = 53;

  // Map snapshot
  try {
    const map = mapRef?.current || mapRef;
    let canvas;
    if (map?.getCanvas) canvas = map.getCanvas();
    else if (map?._canvas) canvas = map._canvas;

    if (canvas) {
      const imgData = canvas.toDataURL('image/jpeg', 0.85);
      const mapW = CONTENT_W;
      const mapH = Math.min(mapW * (canvas.height / canvas.width), 90);
      doc.addImage(imgData, 'JPEG', MARGIN, y, mapW, mapH);
      y += mapH + 8;
    }
  } catch (err) {
    y += 5;
  }

  // Summary stats box
  doc.setFillColor(...LIGHT_GREEN);
  doc.roundedRect(MARGIN, y, CONTENT_W, 24, 3, 3, 'F');

  const stats = [
    { label: 'Trees Planted', value: `${trees.length}` },
    { label: 'Species', value: `${uniqueSpeciesCount}` },
    { label: 'CO2/yr', value: formatCO2(co2) },
    { label: 'Canopy', value: `${fmtNum(canopyArea)} m\u00B2` },
    { label: 'Cooling', value: `-${tempReduction.toFixed(1)}\u00B0C` },
  ];

  const colW = CONTENT_W / stats.length;
  stats.forEach((stat, i) => {
    const cx = MARGIN + colW * i + colW / 2;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 70, 20);
    doc.text(stat.value, cx, y + 10, { align: 'center' });
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 120, 80);
    doc.text(stat.label, cx, y + 17, { align: 'center' });
  });

  y += 32;

  // Key forestry metrics summary
  y = addSectionHeader(doc, y, 'Stand Overview');

  const stand = currentProjection.stand;
  const overviewMetrics = [
    ['Projected Area', `${stand.areaAcres?.toFixed(2) || '?'} acres`],
    ['Trees per Acre', `${stand.treesPerAcre || '?'}`],
    ['Basal Area', `${stand.basalAreaSqFt || '?'} sq ft/acre`],
    ['Stand Density Index', `${stand.sdi || '?'} / ${stand.maxSdi || '?'}`],
    ['Stocking Level', stand.stockingLevel || '?'],
    ['Context', stand.contextLabel || '?'],
    ['Management', prescription?.name || 'No Management'],
  ];

  doc.setFontSize(9);
  overviewMetrics.forEach(([label, val], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(...ROW_ALT);
      doc.rect(MARGIN, y - 3.5, CONTENT_W, 6, 'F');
    }
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...HEADER_TEXT);
    doc.text(label, MARGIN + 2, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK_TEXT);
    doc.text(val, MARGIN + 80, y);
    y += 6;
  });

  addPageFooter(doc, 1, totalPages, pName);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 2: Species Breakdown
  // ═══════════════════════════════════════════════════════════════════════
  doc.addPage();
  y = MARGIN + 5;
  y = addSectionHeader(doc, y, 'Species Breakdown');

  // Table header
  doc.setFillColor(220, 235, 220);
  doc.rect(MARGIN, y - 3, CONTENT_W, 6, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...HEADER_TEXT);
  const cols = [
    { x: 2, label: 'Species' },
    { x: 55, label: 'Scientific Name' },
    { x: 100, label: 'Qty' },
    { x: 112, label: '% Stand' },
    { x: 126, label: 'Growth' },
    { x: 143, label: 'Ht (ft)' },
    { x: 158, label: 'Product' },
  ];
  cols.forEach(c => doc.text(c.label, MARGIN + c.x, y));
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);

  speciesList.forEach((sp, i) => {
    if (y > PAGE_H - 30) return;
    if (i % 2 === 0) {
      doc.setFillColor(...ROW_ALT);
      doc.rect(MARGIN, y - 3, CONTENT_W, 5.5, 'F');
    }

    const pctOfStand = ((sp.count / trees.length) * 100).toFixed(1);
    const product = classifyProduct(sp.maxDbhInches || 20, sp.speciesGroup || 'default');

    doc.setTextColor(...DARK_TEXT);
    doc.text(String(sp.name || 'Unknown').substring(0, 28), MARGIN + 2, y);
    doc.setTextColor(100, 120, 100);
    doc.text(String(sp.scientificName || '').substring(0, 22), MARGIN + 55, y);
    doc.setTextColor(...DARK_TEXT);
    doc.text(String(sp.count), MARGIN + 100, y);
    doc.text(`${pctOfStand}%`, MARGIN + 112, y);

    const rate = sp.growthRate || 'moderate';
    if (rate === 'fast') doc.setTextColor(16, 120, 60);
    else if (rate === 'slow') doc.setTextColor(160, 100, 20);
    else doc.setTextColor(80, 100, 80);
    doc.text(rate.charAt(0).toUpperCase() + rate.slice(1), MARGIN + 126, y);

    doc.setTextColor(...DARK_TEXT);
    doc.text(`${sp.matureHeightFt || '?'}`, MARGIN + 143, y);
    doc.text(product, MARGIN + 158, y);

    y += 5.5;
  });

  addPageFooter(doc, 2, totalPages, pName);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 3: Growth Projections
  // ═══════════════════════════════════════════════════════════════════════
  doc.addPage();
  y = MARGIN + 5;
  y = addSectionHeader(doc, y, 'Growth Projections');

  // Decade table
  doc.setFillColor(220, 235, 220);
  doc.rect(MARGIN, y - 3, CONTENT_W, 6, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...HEADER_TEXT);

  const growthCols = [
    { x: 2, label: 'Year' },
    { x: 18, label: 'Alive' },
    { x: 35, label: 'BA/ac' },
    { x: 52, label: 'SDI' },
    { x: 65, label: 'QMD' },
    { x: 78, label: 'Vol (BF)' },
    { x: 100, label: 'Biomass' },
    { x: 122, label: 'Carbon' },
    { x: 143, label: 'Stocking' },
  ];
  growthCols.forEach(c => doc.text(c.label, MARGIN + c.x, y));
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);

  timeSeries.forEach((ts, i) => {
    if (y > PAGE_H - 50) return;
    if (i % 2 === 0) {
      doc.setFillColor(...ROW_ALT);
      doc.rect(MARGIN, y - 3, CONTENT_W, 5.5, 'F');
    }
    const s = ts.stand;
    doc.setTextColor(...DARK_TEXT);
    doc.text(String(ts.year), MARGIN + 2, y);
    doc.text(String(s.aliveTrees), MARGIN + 18, y);
    doc.text(String(s.basalAreaSqFt || 0), MARGIN + 35, y);
    doc.text(String(s.sdi || 0), MARGIN + 52, y);
    doc.text(String(s.qmd || 0), MARGIN + 65, y);
    doc.text(fmtNum(s.totalVolumeBF || 0), MARGIN + 78, y);
    doc.text(fmtNum(s.totalBiomassLbs || 0), MARGIN + 100, y);
    doc.text(fmtNum(s.totalCarbonLbs || 0), MARGIN + 122, y);
    doc.setTextColor(80, 120, 80);
    doc.text(s.stockingLevel || '', MARGIN + 143, y);
    y += 5.5;
  });

  y += 8;

  // Carbon trajectory simple bar chart
  if (y < PAGE_H - 70) {
    y = addSectionHeader(doc, y, 'Carbon Sequestration Trajectory');

    const maxCarbon = Math.max(...timeSeries.map(t => t.stand.totalCo2Lbs || 0), 1);
    const barMaxW = CONTENT_W - 35;

    timeSeries.forEach((ts) => {
      if (y > PAGE_H - 25) return;
      const val = ts.stand.totalCo2Lbs || 0;
      const barW = Math.max(1, (val / maxCarbon) * barMaxW);

      doc.setFillColor(60, 160, 80);
      doc.roundedRect(MARGIN + 20, y - 3, barW, 5, 1.5, 1.5, 'F');

      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...HEADER_TEXT);
      doc.text(`Yr ${ts.year}`, MARGIN, y);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...DARK_TEXT);
      const label = val >= 2000 ? `${(val / 2204.62).toFixed(1)} tonnes CO2` : `${fmtNum(val)} lbs CO2`;
      doc.text(label, MARGIN + 22 + barW + 2, y);

      y += 7;
    });
  }

  addPageFooter(doc, 3, totalPages, pName);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 4: Management Schedule + Financial Analysis
  // ═══════════════════════════════════════════════════════════════════════
  doc.addPage();
  y = MARGIN + 5;
  y = addSectionHeader(doc, y, 'Management Schedule & Financial Analysis');

  // Prescription info
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...MED_GREEN);
  doc.text(`Prescription: ${prescription?.name || 'No Management'}`, MARGIN, y);
  y += 5;
  if (prescription?.description) {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    const descLines = doc.splitTextToSize(prescription.description, CONTENT_W);
    doc.text(descLines, MARGIN, y);
    y += descLines.length * 3.5 + 3;
  }

  // Actions timeline
  if (prescription?.actions?.length > 0) {
    y += 2;
    doc.setFillColor(220, 235, 220);
    doc.rect(MARGIN, y - 3, CONTENT_W, 6, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...HEADER_TEXT);
    doc.text('Year', MARGIN + 2, y);
    doc.text('Action', MARGIN + 20, y);
    doc.text('Type', MARGIN + 80, y);
    doc.text('Removal %', MARGIN + 110, y);
    doc.text('Revenue', MARGIN + 140, y);
    y += 6;

    doc.setFont('helvetica', 'normal');

    // Get enriched harvest events
    const harvestEvents = projection80.harvestEvents || [];
    const enrichedEvents = harvestEvents.map(ev => enrichHarvestEvent(ev, ev.treeDetails));

    prescription.actions.forEach((action, i) => {
      if (y > PAGE_H - 50) return;
      if (i % 2 === 0) {
        doc.setFillColor(...ROW_ALT);
        doc.rect(MARGIN, y - 3, CONTENT_W, 5.5, 'F');
      }
      doc.setTextColor(...DARK_TEXT);
      doc.text(String(action.year), MARGIN + 2, y);
      doc.text(String(action.label || action.type), MARGIN + 20, y);
      doc.text(String(action.type), MARGIN + 80, y);
      doc.text(`${Math.round((action.removePct || 0) * 100)}%`, MARGIN + 110, y);

      const matchEvent = enrichedEvents.find(e => e.year === action.year);
      const rev = matchEvent?.revenue || 0;
      if (rev > 0) {
        doc.setTextColor(16, 120, 60);
        doc.text(fmtDollar(rev), MARGIN + 140, y);
      } else {
        doc.setTextColor(...MUTED);
        doc.text('$0', MARGIN + 140, y);
      }
      y += 5.5;
    });

    y += 6;

    // Investment analysis
    const finance = analyzeInvestment(
      harvestEvents.map(ev => enrichHarvestEvent(ev, ev.treeDetails)),
      projection80.stand.areaAcres,
      80,
      {},
      0.04
    );

    if (finance) {
      y = addSectionHeader(doc, y, 'Investment Analysis');

      const finRows = [
        ['Establishment Cost', fmtDollar(finance.establishmentCost)],
        ['Total Costs', fmtDollar(finance.totalCosts)],
        ['Total Harvest Revenue', fmtDollar(finance.totalRevenue)],
        ['Net Income', fmtDollar(finance.netIncome)],
        ['NPV (4%)', fmtDollar(finance.npv)],
        ['NPV/acre', fmtDollar(finance.npvPerAcre)],
        ['LEV/acre', fmtDollar(finance.levPerAcre)],
        ['IRR', finance.irr != null ? `${(finance.irr * 100).toFixed(1)}%` : 'N/A'],
      ];

      doc.setFontSize(9);
      finRows.forEach(([label, val], i) => {
        if (i % 2 === 0) {
          doc.setFillColor(...ROW_ALT);
          doc.rect(MARGIN, y - 3.5, CONTENT_W / 2, 6, 'F');
        }
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...HEADER_TEXT);
        doc.text(label, MARGIN + 2, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK_TEXT);
        doc.text(val, MARGIN + 65, y);
        y += 6;
      });
    }
  } else {
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text('No active management — stand develops naturally.', MARGIN, y);
    y += 8;
  }

  addPageFooter(doc, 4, totalPages, pName);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 5: Environmental Impact
  // ═══════════════════════════════════════════════════════════════════════
  doc.addPage();
  y = MARGIN + 5;
  y = addSectionHeader(doc, y, 'Environmental Impact');

  // Ecosystem services
  let ecoServices = null;
  try {
    ecoServices = standAnnualServices(currentProjection.trees);
  } catch (e) { /* pass */ }

  if (ecoServices) {
    const ecoRows = [
      ['Stormwater Intercepted', `${fmtNum(ecoServices.stormwater?.gallonsIntercepted || 0)} gal/yr`, `$${fmtNum(ecoServices.stormwater?.annualValue || 0)}/yr`],
      ['Energy Savings', `${(ecoServices.energy?.coolingKwh || 0).toFixed(0)} kWh/yr`, `$${fmtNum(ecoServices.energy?.annualValue || 0)}/yr`],
      ['Air Quality', '', `$${fmtNum(ecoServices.airQuality?.annualValue || 0)}/yr`],
      ['Property Value Uplift', '', `$${fmtNum(ecoServices.property?.annualValue || 0)}/yr`],
      ['Carbon Value', `${fmtNum(ecoServices.carbon?.annualCo2Lbs || 0)} lbs CO2/yr`, `$${fmtNum(ecoServices.carbon?.annualValue || 0)}/yr`],
    ];

    doc.setFontSize(9);
    ecoRows.forEach(([label, metric, val], i) => {
      if (i % 2 === 0) {
        doc.setFillColor(...ROW_ALT);
        doc.rect(MARGIN, y - 3.5, CONTENT_W, 6, 'F');
      }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...HEADER_TEXT);
      doc.text(label, MARGIN + 2, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...DARK_TEXT);
      doc.text(metric, MARGIN + 70, y);
      doc.setTextColor(16, 120, 60);
      doc.text(val, MARGIN + 120, y);
      y += 6;
    });

    const totalEcoValue = ecoServices.totalAnnualValue || 0;
    y += 2;
    doc.setFillColor(220, 240, 220);
    doc.rect(MARGIN, y - 3.5, CONTENT_W, 7, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...MED_GREEN);
    doc.text('Total Ecosystem Services Value', MARGIN + 2, y + 1);
    doc.text(fmtDollar(totalEcoValue), MARGIN + 120, y + 1);
    y += 12;
  }

  // Carbon credit potential
  y = addSectionHeader(doc, y, 'Carbon Credit Potential');

  let ccAnalysis = null;
  try {
    ccAnalysis = analyzeCarbonCredits({
      trees, speciesMap, prescription, siteIndex,
      creditingPeriod: 40, projectType: 'afforestation', creditPrice: 15,
    });
  } catch (e) { /* pass */ }

  if (ccAnalysis) {
    const ccRows = [
      ['Project Type', ccAnalysis.projectType === 'afforestation' ? 'Afforestation/Reforestation' : 'Improved Forest Management'],
      ['Crediting Period', `${ccAnalysis.creditingPeriod} years`],
      ['Gross Credits', `${ccAnalysis.grossCredits.toFixed(1)} tCO2e`],
      ['Buffer Deduction', `-${ccAnalysis.bufferDeduction.toFixed(1)} tCO2e (${ccAnalysis.bufferPercentage}%)`],
      ['Net Issuable Credits', `${ccAnalysis.netCredits.toFixed(1)} tCO2e`],
      ['Est. Revenue (@$15/t)', `$${fmtNum(ccAnalysis.totalRevenue)}`],
      ['Methodology', ccAnalysis.methodology],
    ];

    doc.setFontSize(9);
    ccRows.forEach(([label, val], i) => {
      if (i % 2 === 0) {
        doc.setFillColor(...ROW_ALT);
        doc.rect(MARGIN, y - 3.5, CONTENT_W, 6, 'F');
      }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...HEADER_TEXT);
      doc.text(label, MARGIN + 2, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...DARK_TEXT);
      doc.text(String(val), MARGIN + 70, y);
      y += 6;
    });
  }

  addPageFooter(doc, 5, totalPages, pName);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 6: Methodology Notes
  // ═══════════════════════════════════════════════════════════════════════
  doc.addPage();
  y = MARGIN + 5;
  y = addSectionHeader(doc, y, 'Methodology & Data Sources');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DARK_TEXT);

  const methodSections = [
    {
      title: 'Published Equations',
      items: [
        'Above-ground biomass: Jenkins et al. (2003) national-scale allometric equations, 10 species groups',
        'Stand density: Reineke (1933) Stand Density Index (SDI = TPA * (QMD/10)^1.605)',
        'Height-diameter: Chapman-Richards function calibrated per species group',
        'Ecosystem services: i-Tree Eco annual interception, energy, and air quality rates',
        'Pulpwood volume: Honer, Ker & Alemdag (1983) combined-variable cord equation',
      ],
    },
    {
      title: 'Growth Model',
      items: [
        'Diameter growth rates calibrated against FVS NE/SN/PN variant documentation (Keyser & Dixon 2017)',
        'Competition: density-dependent growth reduction using relative SDI',
        'Crown ratio: tracked per-tree, updated annually by canopy position; drives mortality weighting',
        'Mortality: background rate + density-dependent + crown ratio weighting (suppressed trees die first)',
        'Context: adaptive urban/natural forestry curves blended by planting density and area',
      ],
    },
    {
      title: 'Financial Estimates',
      items: [
        'Stumpage prices: national average by species group and product class (TimberMart-South/North)',
        'Management costs: typical forestry establishment, annual, and cruising assumptions',
        'Investment analysis: NPV, LEV (Land Expectation Value), IRR using real discount rates',
      ],
    },
    {
      title: 'Carbon Credits',
      items: [
        'Methodology alignment: VCS VM0047 (A/R), VCS VM0003 (IFM), ACR, CAR Forest Protocol',
        'Buffer pool: VCS AFOLU Non-Permanence Risk Tool (10-60% based on risk factors)',
        'Leakage: standard IFM leakage deduction (20% of displaced harvesting)',
      ],
    },
    {
      title: 'Limitations',
      items: [
        'Does not model: shade tolerance interactions, climate stress, regeneration, genetic variation',
        'Site index is approximated from soil texture; actual SI requires field measurement',
        'Financial estimates use national averages; local markets vary significantly',
        'Carbon credit estimates require third-party verification for actual issuance',
      ],
    },
  ];

  methodSections.forEach(section => {
    if (y > PAGE_H - 35) return;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MED_GREEN);
    doc.setFontSize(9);
    doc.text(section.title, MARGIN, y);
    y += 4;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK_TEXT);
    doc.setFontSize(7);
    section.items.forEach(item => {
      if (y > PAGE_H - 25) return;
      const lines = doc.splitTextToSize(`\u2022 ${item}`, CONTENT_W - 4);
      doc.text(lines, MARGIN + 2, y);
      y += lines.length * 3 + 1;
    });
    y += 3;
  });

  // Disclaimer
  y = Math.min(y, PAGE_H - 30);
  doc.setFillColor(255, 250, 230);
  doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(140, 100, 20);
  doc.text('DISCLAIMER', MARGIN + 3, y + 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(100, 80, 20);
  const disclaimer = 'This is a planning-grade educational tool. Results should not replace professional timber cruises, financial appraisals, or verified carbon credit assessments. For validation, export the stand as an FVS keyword file and run through USDA FVS Suppose.';
  const dLines = doc.splitTextToSize(disclaimer, CONTENT_W - 6);
  doc.text(dLines, MARGIN + 3, y + 8);

  addPageFooter(doc, 6, totalPages, pName);

  // ─── Download ──────────────────────────────────────────────────────────
  const fileName = (pName).replace(/[^a-z0-9]/gi, '-').toLowerCase();
  doc.save(`${fileName}-report.pdf`);
}
